# Название нашего рабочего процесса. Будет отображаться во вкладке "Actions".
name: Deploy to GitHub Pages

# Триггеры для запуска этого скрипта.
on:
  # 1. Автоматический запуск при пуше в ветку 'main'.
  #    Это хорошая практика: 'main' содержит стабильную версию, которая идет в продакшен.
  push:
    branches:
      - main

  # 2. РУЧНОЙ ЗАПУСК (самое важное для вас).
  #    Позволяет запустить скрипт из интерфейса GitHub в любой момент.
  workflow_dispatch:
    # Добавляем поле для ввода, где можно будет выбрать ветку.
    inputs:
      branch:
        description: 'Ветка для развертывания (deploy)'
        required: true
        default: 'dev' # По умолчанию будет предлагаться ветка 'dev'

# Настройка прав доступа для рабочего процесса.
# Это необходимо, чтобы Actions могли загружать артефакты и публиковать на Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Определяем задачи (jobs), которые будут выполняться.
jobs:
  # Наша единственная задача - развертывание.
  deploy:
    # Указываем, что задача должна запускаться в окружении GitHub Pages.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL будет доступен после выполнения.
    
    # Используем последнюю версию Ubuntu для запуска.
    runs-on: ubuntu-latest
    
    # Шаги, которые будут выполнены в рамках задачи.
    steps:
      # Шаг 1: Клонирование репозитория (Checkout).
      # Мы скачиваем код из нужной ветки в виртуальную машину.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Указываем, какую ветку скачивать.
          # Если скрипт запущен вручную, берем значение из поля ввода.
          # Если запущен автоматически (пушем), берем имя ветки, куда был сделан пуш.
          ref: ${{ github.event.inputs.branch || github.ref }}

      # Шаг 2: Настройка GitHub Pages.
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Шаг 3: Сборка артефакта.
      # Для нашего простого проекта "сборка" - это просто упаковка всех файлов из корня.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем путь к файлам, которые нужно опубликовать.
          # '.' означает корень репозитория.
          path: '.'

      # Шаг 4: Развертывание (деплой) на GitHub Pages.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4